name: Snyk IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for IaC issues
        uses: snyk/actions@v2 # Update to the correct version
        with:
          command: iac test
          args: terraform
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}