name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read        # Permissão para actions/checkout ler o código
      security-events: write  # Para enviar os resultados de Code Scanning
      actions: read           # Necessário para repositórios privados ao fazer upload dos resultados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code test
        # Adiciona --debug para obter mais detalhes e usa "|| true" para evitar falhas que interrompam o pipeline.
        run: snyk code test --sarif --debug > snyk-code.sarif || true

      - name: Snyk Open Source monitor
        # Caso o repositório não possua dependências ou para evitar falhas, utiliza "|| true".
        run: snyk monitor --all-projects || true

      - name: Snyk IaC test and report
        # Se a análise de IaC falhar, o pipeline continua.
        run: snyk iac test --report || true

      - name: Build a Docker image
        # Se o repositório não utilizar Docker, essa etapa pode ser desabilitada ou ajustada.
        run: docker build -t your/image-to-test . || true

      - name: Snyk Container monitor
        # Ajuste "your/image-to-test" e "Dockerfile" conforme sua configuração.
        run: snyk container monitor your/image-to-test --file=Dockerfile || true

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif